language: objective-c
osx_image: xcode10.1
env:
  global:
  - FRAMEWORK_NAME=SQLiteMigrationManager
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - bin/setup
script:
  - travis_retry ./bin/run-tests
before_deploy:
  - carthage build --platform iOS,macOS --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: GdqbvqChOXT/mi7cdj2FblPx3OwVxpUn0QT151Gi9VwWsx4hvL6LUsKLwPpCwcoA21Ua1bW+neFikkGUE60qcIY1APA3gjjPGpY0WmwBM8V1EKtqbeXdWN05A+eT1UFCgS5C/N9JFLPeI3IMO2iAh1450B0XFyrvBlyY3Fp8Ju8Xp/0YLJ6WOjakOUDXY8TSKQcUErp6RMhYSvwudn1wWxr5n9ZK5hH9vQUyrJzwJ/SFO2o4+YFmsFcsFy6g/wX5+u/tJQ0TQbAedGV0XcJ3xd+cLAiuTpeHyWE+Vq2tebFo6vZXk8Uma4t1YdOgnS7lhrrpjoU8jtl6j67lWM/vvFoz1zVLAhJ9e+GACWHdMmnZMhObjsdm5Z/3fwEV3UY29zmSPGTOekSNfagmQDLod7Qw/dDU0RQaUGmoC2BysttkfpgBYqbnbbZq0ufgKpPgmo6vsAtUllsY4gU0PJ6VDEoUN/awF2G+P2Igib6lQ48t3hZKlq8y4jODG+BnUzprkW6IQuQBi/5A918Xul3Lkr0oOp6IS2IsrGB6qxrEKntNAqm+M5FsUvzAI0DqqQ0vFMijsa2r6oiNdw4hYlWPMXGBBHEEI5pc4l3MTRcjx1O6JJx8z760X79vCYi6xOXOaQ+CxjEyV65ZS70aM3/yMeB7a47fliKKlpSzv1p+inM=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: garriguv/SQLiteMigrationManager.swift
    tags: true
